name: singularity_conda_environment
channels:
  - conda-forge
  - bioconda
  - dranew # bcl2fastq
dependencies:
  - r-base=4.0.3
  # ImportError: libdatrie.so.1: cannot open shared object file: No such file or directory
  # Fix using python3.8
  - python=3.8.8
  - snakemake=6.1.1
    # ModuleNotFoundError: No module named 'snakemake_wrapper_utils'
    # Fix installing explicitly snakemake-wrapper-utils
    # wrappers
    # Trimmomatic/pe
  - trimmomatic=0.36
  - pigz=2.6
  - snakemake-wrapper-utils=0.1.3
    # multiqc
  - multiqc=1.10.1
    # trim_galore/pe
  - trim-galore=0.4.5
    # analyse.yaml
  - r-rmarkdown=2.7
  - r-hmisc=4.5_0
  - r-viridis=0.6.0
  - r-rcolorbrewer=1.1_2
  - r-pheatmap=1.0.12
  - r-corrplot=0.84
  - r-dplyr=1.0.5
    # bcl2fastq.yaml
  - bcl2fastq=2.19.0
    # deconvolution.yaml
  - r-immunedeconv=2.0.3
  - bioconductor-deconrnaseq=1.32.0
  - bioconductor-epidish=2.6.0
  - r-mcpcounter=1.1.0
  - r-purrr=0.3.4
  - r-readr=1.4.0
  - r-stringr=1.4.0
  - r-magrittr=2.0.1
    # fastqc.yaml
  - fastqc=0.11.9
    # kallisto.yaml
  - kallisto=0.46.2
  - bioconductor-tximport=1.18.0
  - bioconductor-rhdf5=2.34.0
  - bioconductor-organism.dplyr=1.18.0
  - bioconductor-org.hs.eg.db=3.12.0
  - bioconductor-txdb.hsapiens.ucsc.hg38.knowngene=3.10.0
    # rename.yaml
  - rename=1.601
  - rsem=1.3.3
  - salmon=1.4.0
  - star=2.7.8a

