Output:
 output
Data:
 Data/TCGA_AML

Phenotype_file:
 Data/TCGA_AML/phenotype.csv
Annotation_file:
 MethylationEPIC_v-1-0_B4.csv

Threads:
 14

Do_beta_values:
 "yes"
Array_type: # 450K or EPIC
 450K
  
Do_deconv:
 "yes"
Signature:
 Data/signatures 
